# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
ZSH=$DOTFILES/oh-my-zsh
ZSH_CUSTOM=$DOTFILES/shell/custom-oh-my-zsh
ZSH_THEME="cwoebker"

# oh-my-zsh configuration
DISABLE_AUTO_UPDATE="false"
COMPLETION_WAITING_DOTS="true"

plugins=(cwoebker brew brew-cask catimg fabric gem
	git git-extras github heroku nyan osx pip python
	redis-cli ruby vagrant sublime z cp
	zsh-autosuggestions zsh-syntax-highlighting zsh-navigation-tools)

source $ZSH/oh-my-zsh.sh
source $DOTFILES/shell/path.zsh
source $DOTFILES/shell/config.zsh
source $DOTFILES/shell/functions.zsh
# all of our zsh files
typeset -U alias_files
alias_files=($DOTFILES/**/aliases.zsh)
for file in ${alias_files}
do
  source $file
done
unset alias_files

# activate zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# activate antigen - zsh plugin system
# source /usr/local/share/antigen/antigen.zsh

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

#autoload predict-on
