# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="cwoebker"

# Editor settings
export EDITOR=vim$EDITOR

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(cwoebker brew fabric gem git github heroku osx pip python redis-cli ruby vagrant)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# Terminal 256 colors
export TERM="xterm-256color"

##### PATH #####

# Customize to your needs...

# homebrew priority
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# dotfiles
export PATH=$HOME/.bin:$PATH

##### PYTHON #####

# pyenv
export PYENV_ROOT=/usr/local/opt/pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# PIP & Virtualenv
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
export VIRTUAL_ENV_DISABLE_PROMPT=true

##### RUBY #####

# rbenv
#if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

#Homebrew Gems Install
export PATH=/usr/local/opt/ruby/bin:$PATH

##### NODE #####

# NODE_PATH
export NODE_PATH=/opt/brew/lib/node_modules:$NODE_PATH

