[tools]
node = "24.9.0"
pnpm = "11.0.9"
python = "3.14.1"
ruby = "3.4.8"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
ruby.compile = false

[env]
RUBY_CONFIGURE_OPTS = "--with-libyaml-dir=/opt/homebrew/opt/libyaml"
