#---------------------------------------------------------------------------
MAKEFILE_PATH := $(abspath $(lastword ${MAKEFILE_LIST}))
MAKEFILE_DIR := $(dir ${MAKEFILE_PATH})
#---------------------------------------------------------------------------
BREW := $(shell command -v brew 2> /dev/null)
ZSH := $(shell command -v zsh 2> /dev/null)
TMUX := $(shell command -v tmux 2> /dev/null)

#---------------------------------------------------------------------------
define info_message
    @echo "[ \033[00;34m..\033[0m ] $(1)\n"
endef
define user_message
    @echo "\r  [ \033[0;33m?\033[0m ] $(1)\n"
endef
define fail_message
    @echo "\033[2K  [\033[0;31mFAIL\033[0m] $(1)\n"
  	exit 1
endef
define success_message
    @echo "\r\033[2K  [ \033[00;32mOK\033[0m ] $(1)\n"
endef
#---------------------------------------------------------------------------
print-environment:
	@echo "λ  MAKEFILE_PATH: ${MAKEFILE_PATH}"
	@echo "λ  MAKEFILE_DIR: ${MAKEFILE_DIR}"
#---------------------------------------------------------------------------
install-brew:
ifndef BREW
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	@echo "λ  Found Homebrew: ${BREW}"
endif
#---------------------------------------------------------------------------
install-tmux: install-brew
ifndef TMUX
	brew install tmux
	brew install reattach-to-user-namespace
else
	@echo "λ  Found Tmux: ${TMUX}"
endif
#---------------------------------------------------------------------------
install-zsh: install-brew
ifndef ZSH
	brew install zsh
	@echo "λ  Setting Zsh shell"
	@grep -q -F `which zsh` /etc/shells || echo `which zsh` | sudo tee -a /etc/shells > /dev/null
	@chsh -s `which zsh`
else
	@echo "λ  Found Zsh: ${ZSH}"
endif
#---------------------------------------------------------------------------
install-shell: install-zsh
	$(call info_message,"λ  Linking zsh theme")
	ln -fs ../../cwoebker.zsh-theme ${MAKEFILE_DIR}shell/oh-my-zsh/themes/cwoebker.zsh-theme
#---------------------------------------------------------------------------
install-hosts:
	$(call info_message,"Installing hosts file...")
	#if [ $EUID == 0 ]; then
	#  cat ${MAKEFILE_DIR}custom/customhosts ${MAKEFILE_DIR}osx/zerohosts > /etc/hosts
	#else
	#  user "Need sudo rights to update hosts file"
	#fi
#---------------------------------------------------------------------------
backup-symlinks:
	$(call info_message,"Backing up older symlinks...")
	mv ~/.vimrc ~/.vimrc-bak
	mv ~/.zshrc ~/.zshrc-bak
	mv ~/.vim ~/.vim-bak
	mv ~/.gitconfig ~/.gitconfig-bak
	mv ~/.gitignore ~/.gitignore-bak
	mv ~/.tmux.conf ~/.tmux.conf-bak
#---------------------------------------------------------------------------
install-symlinks: backup-symlinks
	$(call info_message,"Installing symlinks...")
	$(call info_message,"λ  Linking binary files")
	@chmod u+x ${MAKEFILE_DIR}custom/bin/*
	@ln -sf ${MAKEFILE_DIR}custom/bin ~/.bin
	@echo "λ  Linking Zsh configuration"
	@ln -sf ${MAKEFILE_DIR}shell/zshrc ~/.zshrc
	@echo "λ  Linking Tmux configuration"
	@ln -sf ${MAKEFILE_DIR}shell/tmux ~/.tmux.conf
	@echo "λ  Linking Tmuxinator configuration"
	@ln -sf ${MAKEFILE_DIR}custom/tmuxinator ~/.tmuxinator

	@echo "λ  Linking VIM configuration"
	@ln -sf ${MAKEFILE_DIR}editor/vim ~/.vim
	$(call info_message,"Linkiung atom setup...")
	ln -fs ${MAKEFILE_DIR}editor/atom ~/.atom
	$(call info_message,"Linking sublime settings...")
	ln -fs ${MAKEFILE_DIR}editor/sublime/Preferences.sublime-settings "~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
	$(call info_message,"Installing git configs...")
	ln -fs ${MAKEFILE_DIR}git/gitconfig ~/.gitconfig
	ln -fs ${MAKEFILE_DIR}git/gitignore ~/.gitignore
#---------------------------------------------------------------------------
install: print-environment install-shell install-tmux
	$(call success_message,"Installation of cwoebker's dotfiles complete!")
#---------------------------------------------------------------------------


