#---------------------------------------------------------------------------
MAKEFILE_PATH := $(abspath $(lastword ${MAKEFILE_LIST}))
MAKEFILE_DIR := $(dir ${MAKEFILE_PATH})
#---------------------------------------------------------------------------
BREW := $(shell command -v brew 2> /dev/null)
ZSH := $(shell command -v zsh 2> /dev/null)
TMUX := $(shell command -v tmux 2> /dev/null)
#---------------------------------------------------------------------------
print-environment:
	@echo "λ  MAKEFILE_PATH: ${MAKEFILE_PATH}"
	@echo "λ  MAKEFILE_DIR: ${MAKEFILE_DIR}"
#---------------------------------------------------------------------------
install-brew:
ifndef BREW
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	@echo "λ  Found Homebrew: ${BREW}"
endif
#---------------------------------------------------------------------------
install-tmux: install-brew
ifndef TMUX
	brew install tmux
	brew install reattach-to-user-namespace
else
	@echo "λ  Found Tmux: ${TMUX}"
endif
#---------------------------------------------------------------------------
install-zsh: install-brew
ifndef ZSH
	brew install zsh
	@echo "λ  Setting Zsh shell"
	@grep -q -F `which zsh` /etc/shells || echo `which zsh` | sudo tee -a /etc/shells > /dev/null
	@chsh -s `which zsh`
else
	@echo "λ  Found Zsh: ${ZSH}"
endif
#---------------------------------------------------------------------------
backup-symlinks:
	@echo "Backing up older symlinks..."
#---------------------------------------------------------------------------
install-symlinks:
	@echo "Installing symlinks..."
	@echo "λ  Linking VIM configuration"
	@mkdir -p ~/.config/
	@sh -c "[ ! -L ~/.config/nvim ] || rm -r ~/.config/nvim;"
	@sh -c "[ ! -L ~/.vim ] || rm -r ~/.vim;"
	@sh -c "[ ! -L ~/.vimrc ] || rm -r ~/.vimrc;"
	@sh -c "[ ! -L ~/.gvimrc ] || rm -r ~/.gvimrc;"
	@ln -sf ${MAKEFILE_DIR}vim ~/.config/nvim
	@ln -sf ${MAKEFILE_DIR}vim ~/.vim
	@ln -sf ${MAKEFILE_DIR}vim/init.vim ~/.vimrc
	@ln -sf ${MAKEFILE_DIR}vim/gui.vim ~/.gvimrc
	@echo "λ  Linking Zsh configuration"
	@ln -sf ${MAKEFILE_DIR}zsh/zshrc.symlink ~/.zshrc
	@echo "λ  Linking Tmux configuration"
	@ln -sf ${MAKEFILE_DIR}tmux/tmux.conf.symlink ~/.tmux.conf
	@echo "λ  Linking Tig configuration"
	@ln -sf ${MAKEFILE_DIR}tig/tigrc.symlink ~/.tigrc
#---------------------------------------------------------------------------
install: print-environment install-zsh install-tmux install-symlinks
#---------------------------------------------------------------------------